// Shopping glossary used to translate search words, with Hong Kong (Cantonese) terms.
// Rows: [zh, en, de, fr, nl, it]; a cell may list alternatives with "|" — the first is
// used as the translation, all of them are recognised in what you type.
// Longer phrases win over shorter ones ("雞翼" before "雞"), and a Chinese phrase that is
// only partly covered goes to machine translation as a whole.
export const G = [
  // coffee
  ['手搖磨豆機|手動磨豆機', 'manual coffee grinder|hand grinder', 'Handkaffeemühle', 'moulin à café manuel', 'handmatige koffiemolen', 'macinacaffè manuale'],
  ['電動磨豆機', 'electric coffee grinder', 'elektrische Kaffeemühle', 'moulin à café électrique', 'elektrische koffiemolen', 'macinacaffè elettrico'],
  ['磨豆機|咖啡磨', 'coffee grinder|grinder', 'Kaffeemühle', 'moulin à café', 'koffiemolen', 'macinacaffè'],
  ['意式咖啡機|特濃咖啡機', 'espresso machine', 'Espressomaschine', 'machine à expresso', 'espressomachine', 'macchina per espresso'],
  ['咖啡機', 'coffee machine', 'Kaffeemaschine', 'machine à café', 'koffiezetapparaat', 'macchina da caffè'],
  ['咖啡豆', 'coffee beans', 'Kaffeebohnen', 'café en grains', 'koffiebonen', 'caffè in grani'],
  ['咖啡膠囊', 'coffee capsules|coffee pods', 'Kaffeekapseln', 'capsules de café', 'koffiecups', 'capsule caffè'],
  ['手沖壺', 'pour over kettle|gooseneck kettle', 'Schwanenhals Wasserkocher', 'bouilloire col de cygne', 'waterkoker zwanenhals', 'bollitore collo di cigno'],
  ['濾杯', 'coffee dripper|dripper', 'Kaffeefilter Handfilter', 'porte-filtre café', 'koffiefilterhouder', 'filtro caffè'],
  ['濾紙', 'coffee filter paper|coffee filters', 'Kaffeefilterpapier', 'filtres à café', 'koffiefilters', 'filtri caffè'],
  ['咖啡秤', 'coffee scale', 'Kaffeewaage', 'balance à café', 'koffieweegschaal', 'bilancia caffè'],
  ['奶泡機|打奶器', 'milk frother', 'Milchaufschäumer', 'mousseur à lait', 'melkopschuimer', 'montalatte'],
  ['法壓壺', 'french press|cafetiere', 'French Press', 'cafetière à piston', 'cafetière', 'caffettiera a pistone'],
  ['摩卡壺', 'moka pot', 'Espressokocher', 'cafetière italienne', 'percolator', 'moka'],
  ['咖啡', 'coffee', 'Kaffee', 'café', 'koffie', 'caffè'],
  ['冷萃', 'cold brew', 'Cold Brew', 'cold brew', 'cold brew', 'cold brew'],
  ['咖啡杯', 'coffee mug|coffee cup', 'Kaffeebecher', 'tasse à café', 'koffiemok', 'tazza da caffè'],
  ['保溫杯|保溫瓶', 'vacuum flask|thermos|insulated bottle', 'Thermosflasche', 'bouteille isotherme', 'thermosfles', 'thermos'],
  ['水樽|水壺', 'water bottle', 'Trinkflasche', 'gourde', 'drinkfles', 'borraccia'],
  ['無咖啡因|低咖啡因', 'decaf', 'entkoffeiniert', 'décaféiné', 'cafeïnevrij', 'decaffeinato'],
  ['胡椒磨', 'pepper mill|pepper grinder', 'Pfeffermühle', 'moulin à poivre', 'pepermolen', 'macinapepe'],
  // household & personal care
  ['洗衣珠|洗衣膠囊', 'laundry pods|laundry capsules', 'Waschmittel Pods', 'capsules de lessive', 'wasmiddel capsules', 'capsule detersivo'],
  ['洗衣液|洗衣粉', 'laundry detergent', 'Waschmittel', 'lessive', 'wasmiddel', 'detersivo bucato'],
  ['洗潔精', 'washing up liquid|dish soap', 'Spülmittel', 'liquide vaisselle', 'afwasmiddel', 'detersivo piatti'],
  ['洗碗機洗滌塊|洗碗粒', 'dishwasher tablets', 'Spülmaschinentabs', 'tablettes lave-vaisselle', 'vaatwastabletten', 'pastiglie lavastoviglie'],
  ['廁紙|衛生紙', 'toilet paper|toilet roll', 'Toilettenpapier', 'papier toilette', 'toiletpapier', 'carta igienica'],
  ['廚房紙', 'kitchen roll|paper towels', 'Küchenrolle', 'essuie-tout', 'keukenrol', 'carta da cucina'],
  ['紙巾', 'tissues', 'Taschentücher', 'mouchoirs', 'tissues', 'fazzoletti'],
  ['毛巾', 'towel', 'Handtuch', 'serviette', 'handdoek', 'asciugamano'],
  ['床單', 'bed sheet', 'Bettlaken', 'drap', 'laken', 'lenzuolo'],
  ['枕頭', 'pillow', 'Kopfkissen', 'oreiller', 'hoofdkussen', 'cuscino'],
  ['羽絨被', 'duvet', 'Bettdecke', 'couette', 'dekbed', 'piumone'],
  ['吸塵機', 'vacuum cleaner|hoover', 'Staubsauger', 'aspirateur', 'stofzuiger', 'aspirapolvere'],
  ['空氣清新機', 'air purifier', 'Luftreiniger', "purificateur d'air", 'luchtreiniger', "purificatore d'aria"],
  ['抽濕機', 'dehumidifier', 'Luftentfeuchter', 'déshumidificateur', 'luchtontvochtiger', 'deumidificatore'],
  ['風筒', 'hair dryer|hairdryer', 'Haartrockner', 'sèche-cheveux', 'haardroger', 'asciugacapelli'],
  ['電飯煲', 'rice cooker', 'Reiskocher', 'cuiseur à riz', 'rijstkoker', 'cuociriso'],
  ['氣炸鍋', 'air fryer', 'Heißluftfritteuse', 'friteuse sans huile', 'airfryer', 'friggitrice ad aria'],
  ['電熱水煲|熱水煲', 'electric kettle|kettle', 'Wasserkocher', 'bouilloire électrique', 'waterkoker', 'bollitore elettrico'],
  ['平底鑊|煎鍋', 'frying pan', 'Bratpfanne', 'poêle', 'koekenpan', 'padella'],
  ['菜刀', 'kitchen knife', 'Küchenmesser', 'couteau de cuisine', 'keukenmes', 'coltello da cucina'],
  ['洗頭水|洗髮水', 'shampoo', 'Shampoo', 'shampooing', 'shampoo', 'shampoo'],
  ['護髮素', 'conditioner', 'Spülung', 'après-shampooing', 'conditioner', 'balsamo'],
  ['沐浴露', 'shower gel|body wash', 'Duschgel', 'gel douche', 'douchegel', 'bagnoschiuma'],
  ['電動牙刷', 'electric toothbrush', 'elektrische Zahnbürste', 'brosse à dents électrique', 'elektrische tandenborstel', 'spazzolino elettrico'],
  ['牙刷', 'toothbrush', 'Zahnbürste', 'brosse à dents', 'tandenborstel', 'spazzolino'],
  ['牙膏', 'toothpaste', 'Zahnpasta', 'dentifrice', 'tandpasta', 'dentifricio'],
  ['防曬', 'sunscreen|sun cream', 'Sonnencreme', 'crème solaire', 'zonnebrand', 'crema solare'],
  ['尿片', 'nappies|diapers', 'Windeln', 'couches', 'luiers', 'pannolini'],
  ['垃圾袋', 'bin bags|bin liners', 'Müllbeutel', 'sacs poubelle', 'vuilniszakken', 'sacchi per la spazzatura'],
  ['保鮮紙', 'cling film', 'Frischhaltefolie', 'film alimentaire', 'vershoudfolie', 'pellicola trasparente'],
  ['錫紙', 'tin foil|aluminium foil', 'Alufolie', 'papier aluminium', 'aluminiumfolie', 'carta stagnola'],
  ['保鮮盒', 'food storage containers|food containers', 'Frischhaltedosen', 'boîtes de conservation', 'vershouddozen', 'contenitori per alimenti'],
  ['濕紙巾', 'wet wipes|baby wipes', 'Feuchttücher', 'lingettes', 'vochtige doekjes', 'salviette umidificate'],
  ['洗手液', 'hand wash|hand soap', 'Flüssigseife', 'savon pour les mains', 'handzeep', 'sapone per le mani'],
  ['番梘|肥皂', 'soap|bar soap', 'Seife', 'savon', 'zeep', 'sapone'],
  ['柔順劑', 'fabric softener|fabric conditioner', 'Weichspüler', 'adoucissant', 'wasverzachter', 'ammorbidente'],
  ['漂白水', 'bleach', 'Bleichmittel', 'eau de javel', 'bleekmiddel', 'candeggina'],
  ['消毒噴霧|消毒液', 'disinfectant', 'Desinfektionsmittel', 'désinfectant', 'desinfectiemiddel', 'disinfettante'],
  ['驅蚊|蚊怕水', 'insect repellent|mosquito repellent', 'Mückenschutz', 'anti-moustique', 'muggenspray', 'antizanzare'],
  ['電芯|電池', 'batteries', 'Batterien', 'piles', 'batterijen', 'batterie'],
  ['燈膽|燈泡', 'light bulb', 'Glühbirne', 'ampoule', 'gloeilamp', 'lampadina'],
  ['衣架', 'coat hangers|clothes hangers|hangers|coat hanger', 'Kleiderbügel', 'cintres', 'kledinghangers', 'grucce'],
  ['晾衫架', 'clothes airer|drying rack', 'Wäscheständer', 'étendoir', 'droogrek', 'stendibiancheria'],
  ['地拖', 'mop', 'Wischmopp', 'serpillière', 'mop', 'mocio'],
  ['掃把|掃帚', 'broom', 'Besen', 'balai', 'bezem', 'scopa'],
  ['砧板', 'chopping board', 'Schneidebrett', 'planche à découper', 'snijplank', 'tagliere'],
  ['筷子', 'chopsticks', 'Essstäbchen', 'baguettes chinoises', 'eetstokjes', 'bacchette'],
  ['匙羹|湯匙', 'spoons', 'Löffel', 'cuillères', 'lepels', 'cucchiai'],
  ['碗', 'bowls', 'Schüsseln', 'bols', 'kommen', 'ciotole'],
  ['碟', 'plates', 'Teller', 'assiettes', 'borden', 'piatti'],
  ['酒杯', 'wine glasses', 'Weingläser', 'verres à vin', 'wijnglazen', 'calici da vino'],
  ['煲|湯煲', 'saucepan|stock pot', 'Kochtopf', 'casserole', 'kookpan', 'pentola'],
  ['鑊', 'wok', 'Wok', 'wok', 'wok', 'wok'],
  ['床褥', 'mattress', 'Matratze', 'matelas', 'matras', 'materasso'],
  ['被套', 'duvet cover', 'Bettbezug', 'housse de couette', 'dekbedovertrek', 'copripiumino'],
  ['窗簾', 'curtains', 'Vorhänge', 'rideaux', 'gordijnen', 'tende'],
  ['地氈', 'rug', 'Teppich', 'tapis', 'vloerkleed', 'tappeto'],
  ['衣櫃', 'wardrobe', 'Kleiderschrank', 'armoire', 'kledingkast', 'armadio'],
  ['梳化', 'sofa', 'Sofa', 'canapé', 'bank', 'divano'],
  ['書枱|書檯', 'desk', 'Schreibtisch', 'bureau', 'bureau', 'scrivania'],
  ['枱燈|檯燈', 'desk lamp', 'Schreibtischlampe', 'lampe de bureau', 'bureaulamp', 'lampada da scrivania'],
  ['椅子|櫈', 'chair', 'Stuhl', 'chaise', 'stoel', 'sedia'],
  ['蠟燭', 'candles', 'Kerzen', 'bougies', 'kaarsen', 'candele'],
  ['香薰機', 'aroma diffuser', 'Aroma Diffuser', 'diffuseur', 'aroma diffuser', 'diffusore di aromi'],
  // appliances
  ['雪櫃', 'fridge', 'Kühlschrank', 'réfrigérateur', 'koelkast', 'frigorifero'],
  ['洗衣機', 'washing machine', 'Waschmaschine', 'lave-linge', 'wasmachine', 'lavatrice'],
  ['乾衣機', 'tumble dryer', 'Wäschetrockner', 'sèche-linge', 'wasdroger', 'asciugatrice'],
  ['冷氣機', 'air conditioner', 'Klimaanlage', 'climatiseur', 'airco', 'condizionatore'],
  ['風扇', 'electric fan|desk fan', 'Ventilator', 'ventilateur', 'ventilator', 'ventilatore'],
  ['暖爐', 'heater|electric heater', 'Heizlüfter', 'radiateur électrique', 'elektrische kachel', 'stufetta elettrica'],
  ['微波爐', 'microwave', 'Mikrowelle', 'micro-ondes', 'magnetron', 'microonde'],
  ['焗爐', 'oven', 'Backofen', 'four', 'oven', 'forno'],
  ['多士爐', 'toaster', 'Toaster', 'grille-pain', 'broodrooster', 'tostapane'],
  ['攪拌機', 'blender', 'Standmixer', 'blender', 'blender', 'frullatore'],
  ['榨汁機', 'juicer', 'Entsafter', 'centrifugeuse', 'sapcentrifuge', 'centrifuga'],
  ['洗碗機', 'dishwasher', 'Geschirrspüler', 'lave-vaisselle', 'vaatwasser', 'lavastoviglie'],
  ['電磁爐', 'induction hob', 'Induktionskochplatte', 'plaque à induction', 'inductiekookplaat', 'piastra a induzione'],
  ['慢煮鍋', 'slow cooker', 'Schongarer', 'mijoteuse', 'slowcooker', 'slow cooker'],
  ['熨斗', 'steam iron', 'Bügeleisen', 'fer à repasser', 'strijkijzer', 'ferro da stiro'],
  ['掛燙機', 'garment steamer', 'Dampfglätter', 'défroisseur', 'kledingstomer', 'stiratrice verticale'],
  ['電熱毯', 'electric blanket', 'Heizdecke', 'couverture chauffante', 'elektrische deken', 'coperta elettrica'],
  ['電動鬚刨|電鬚刨', 'electric shaver', 'Elektrorasierer', 'rasoir électrique', 'scheerapparaat', 'rasoio elettrico'],
  ['鬚刨|剃鬚刀', 'razor', 'Rasierer', 'rasoir', 'scheermes', 'rasoio'],
  ['直髮器|直髮夾', 'hair straightener', 'Glätteisen', 'lisseur', 'stijltang', 'piastra per capelli'],
  ['捲髮器|卷髮棒|捲髮棒', 'curling iron|curling tongs', 'Lockenstab', 'fer à boucler', 'krultang', 'arricciacapelli'],
  ['體重磅|電子磅', 'bathroom scales', 'Personenwaage', 'pèse-personne', 'personenweegschaal', 'bilancia pesapersone'],
  ['廚房磅', 'kitchen scales', 'Küchenwaage', 'balance de cuisine', 'keukenweegschaal', 'bilancia da cucina'],
  ['沖牙機|洗牙機', 'water flosser', 'Munddusche', 'hydropulseur', 'monddouche', 'idropulsore'],
  // personal care & pharmacy
  ['牙線', 'dental floss', 'Zahnseide', 'fil dentaire', 'flosdraad', 'filo interdentale'],
  ['漱口水', 'mouthwash', 'Mundspülung', 'bain de bouche', 'mondwater', 'collutorio'],
  ['面霜', 'face cream|moisturiser', 'Gesichtscreme', 'crème visage', 'gezichtscrème', 'crema viso'],
  ['潤膚露|潤膚乳', 'body lotion', 'Bodylotion', 'lait corporel', 'bodylotion', 'crema corpo'],
  ['潤唇膏', 'lip balm', 'Lippenbalsam', 'baume à lèvres', 'lippenbalsem', 'balsamo labbra'],
  ['洗面奶|洗面膏|潔面乳', 'face wash|facial cleanser', 'Waschgel', 'nettoyant visage', 'gezichtsreiniger', 'detergente viso'],
  ['卸妝', 'make-up remover|makeup remover', 'Make-up-Entferner', 'démaquillant', 'make-up remover', 'struccante'],
  ['面膜', 'face mask|sheet mask', 'Gesichtsmaske', 'masque visage', 'gezichtsmasker', 'maschera viso'],
  ['口罩', 'surgical masks|face masks', 'medizinische Masken', 'masques chirurgicaux', 'mondkapjes', 'mascherine'],
  ['香水', 'perfume', 'Parfum', 'parfum', 'parfum', 'profumo'],
  ['止汗劑|爽身香體|體香劑', 'deodorant', 'Deo', 'déodorant', 'deodorant', 'deodorante'],
  ['衛生巾', 'sanitary pads|sanitary towels', 'Damenbinden', 'serviettes hygiéniques', 'maandverband', 'assorbenti'],
  ['棉花棒', 'cotton buds', 'Wattestäbchen', 'cotons-tiges', 'wattenstaafjes', 'cotton fioc'],
  ['化妝棉', 'cotton pads', 'Wattepads', 'cotons démaquillants', 'wattenschijfjes', 'dischetti di cotone'],
  ['膠布|藥水膠布', 'plasters', 'Pflaster', 'pansements', 'pleisters', 'cerotti'],
  ['必理痛|撲熱息痛', 'paracetamol', 'Paracetamol', 'paracétamol', 'paracetamol', 'paracetamolo'],
  ['止痛藥', 'painkillers', 'Schmerzmittel', 'antidouleur', 'pijnstillers', 'antidolorifici'],
  ['維他命', 'vitamins', 'Vitamine', 'vitamines', 'vitamines', 'vitamine'],
  ['魚油', 'fish oil', 'Fischöl', 'huile de poisson', 'visolie', 'olio di pesce'],
  ['益生菌', 'probiotics', 'Probiotika', 'probiotiques', 'probiotica', 'probiotici'],
  ['指甲鉗', 'nail clippers', 'Nagelknipser', 'coupe-ongles', 'nagelknipper', 'tagliaunghie'],
  ['髮夾', 'hair clips', 'Haarspangen', 'pinces à cheveux', 'haarspeldjes', 'mollette per capelli'],
  ['梳', 'hairbrush|comb', 'Haarbürste', 'brosse à cheveux', 'haarborstel', 'spazzola per capelli'],
  // baby & pets
  ['嬰兒車', 'pushchair|stroller|pram', 'Kinderwagen', 'poussette', 'kinderwagen', 'passeggino'],
  ['奶樽', 'baby bottle', 'Babyflasche', 'biberon', 'babyfles', 'biberon'],
  ['奶嘴', 'dummy|pacifier', 'Schnuller', 'tétine', 'speen', 'ciuccio'],
  ['奶粉', 'baby formula|formula milk', 'Säuglingsnahrung', 'lait infantile', 'zuigelingenvoeding', 'latte in polvere'],
  ['嬰兒', 'baby', 'Baby', 'bébé', 'baby', 'neonato'],
  ['貓糧', 'cat food', 'Katzenfutter', 'nourriture pour chat', 'kattenvoer', 'cibo per gatti'],
  ['狗糧', 'dog food', 'Hundefutter', 'nourriture pour chien', 'hondenvoer', 'cibo per cani'],
  ['貓砂', 'cat litter', 'Katzenstreu', 'litière pour chat', 'kattenbakvulling', 'lettiera per gatti'],
  // groceries
  ['燕麥奶', 'oat milk', 'Haferdrink', "lait d'avoine", 'havermelk', "latte d'avena"],
  ['豆奶|豆漿', 'soy milk', 'Sojamilch', 'lait de soja', 'sojamelk', 'latte di soia'],
  ['牛奶', 'milk', 'Milch', 'lait', 'melk', 'latte'],
  ['雞蛋', 'eggs', 'Eier', 'œufs', 'eieren', 'uova'],
  ['麵包', 'bread', 'Brot', 'pain', 'brood', 'pane'],
  ['白米|大米', 'rice', 'Reis', 'riz', 'rijst', 'riso'],
  ['意粉', 'pasta|spaghetti', 'Nudeln', 'pâtes', 'pasta', 'pasta'],
  ['即食麵|公仔麵', 'instant noodles', 'Instantnudeln', 'nouilles instantanées', 'instant noedels', 'noodles istantanei'],
  ['朱古力|巧克力', 'chocolate', 'Schokolade', 'chocolat', 'chocolade', 'cioccolato'],
  ['餅乾', 'biscuits|cookies', 'Kekse', 'biscuits', 'koekjes', 'biscotti'],
  ['茶葉|茶包', 'tea', 'Tee', 'thé', 'thee', 'tè'],
  ['橄欖油', 'olive oil', 'Olivenöl', "huile d'olive", 'olijfolie', "olio d'oliva"],
  ['芝士', 'cheese', 'Käse', 'fromage', 'kaas', 'formaggio'],
  ['牛油', 'butter', 'Butter', 'beurre', 'boter', 'burro'],
  ['乳酪', 'yogurt|yoghurt', 'Joghurt', 'yaourt', 'yoghurt', 'yogurt'],
  ['礦泉水', 'mineral water', 'Mineralwasser', 'eau minérale', 'mineraalwater', 'acqua minerale'],
  ['紅酒', 'red wine', 'Rotwein', 'vin rouge', 'rode wijn', 'vino rosso'],
  ['白酒', 'white wine', 'Weißwein', 'vin blanc', 'witte wijn', 'vino bianco'],
  ['啤酒', 'beer', 'Bier', 'bière', 'bier', 'birra'],
  ['橙汁', 'orange juice', 'Orangensaft', "jus d'orange", 'sinaasappelsap', "succo d'arancia"],
  ['蘋果汁', 'apple juice', 'Apfelsaft', 'jus de pomme', 'appelsap', 'succo di mela'],
  ['果汁', 'juice', 'Saft', 'jus', 'sap', 'succo'],
  ['汽水', 'soft drink|fizzy drink', 'Limonade', 'soda', 'frisdrank', 'bibita'],
  ['咖啡粉', 'ground coffee', 'gemahlener Kaffee', 'café moulu', 'gemalen koffie', 'caffè macinato'],
  ['糖', 'sugar', 'Zucker', 'sucre', 'suiker', 'zucchero'],
  ['鹽', 'salt', 'Salz', 'sel', 'zout', 'sale'],
  ['麵粉', 'flour', 'Mehl', 'farine', 'bloem', 'farina'],
  ['蜜糖|蜂蜜', 'honey', 'Honig', 'miel', 'honing', 'miele'],
  ['果醬', 'jam', 'Marmelade', 'confiture', 'jam', 'marmellata'],
  ['花生醬', 'peanut butter', 'Erdnussbutter', 'beurre de cacahuète', 'pindakaas', 'burro di arachidi'],
  ['粟米片|早餐穀物', 'cornflakes|cereal|corn flakes', 'Cornflakes', 'corn flakes', 'cornflakes', 'corn flakes'],
  ['薯片', 'crisps|chips', 'Chips', 'chips', 'chips', 'patatine'],
  ['雪糕', 'ice cream', 'Eis', 'glace', 'ijs', 'gelato'],
  ['雞胸', 'chicken breast', 'Hühnerbrust', 'blanc de poulet', 'kipfilet', 'petto di pollo'],
  ['雞肉|雞', 'chicken', 'Hähnchen', 'poulet', 'kip', 'pollo'],
  ['豬肉', 'pork', 'Schweinefleisch', 'porc', 'varkensvlees', 'maiale'],
  ['牛肉', 'beef', 'Rindfleisch', 'bœuf', 'rundvlees', 'manzo'],
  ['三文魚', 'salmon', 'Lachs', 'saumon', 'zalm', 'salmone'],
  ['香蕉', 'bananas', 'Bananen', 'bananes', 'bananen', 'banane'],
  ['橙', 'oranges', 'Orangen', 'oranges', 'sinaasappels', 'arance'],
  ['番茄|蕃茄', 'tomatoes', 'Tomaten', 'tomates', 'tomaten', 'pomodori'],
  ['薯仔|馬鈴薯', 'potatoes', 'Kartoffeln', 'pommes de terre', 'aardappelen', 'patate'],
  ['洋蔥', 'onions', 'Zwiebeln', 'oignons', 'uien', 'cipolle'],
  // fruit & vegetables
  ['士多啤梨|草莓', 'strawberries', 'Erdbeeren', 'fraises', 'aardbeien', 'fragole'],
  ['車厘子', 'cherries', 'Kirschen', 'cerises', 'kersen', 'ciliegie'],
  ['提子乾|葡萄乾', 'raisins', 'Rosinen', 'raisins secs', 'rozijnen', 'uvetta'],
  ['提子|葡萄', 'grapes', 'Trauben', 'raisins', 'druiven', 'uva'],
  ['藍莓', 'blueberries', 'Heidelbeeren', 'myrtilles', 'blauwe bessen', 'mirtilli'],
  ['紅桑子|覆盆子', 'raspberries', 'Himbeeren', 'framboises', 'frambozen', 'lamponi'],
  ['菠蘿', 'pineapple', 'Ananas', 'ananas', 'ananas', 'ananas'],
  ['奇異果', 'kiwi fruit|kiwi', 'Kiwi', 'kiwi', 'kiwi', 'kiwi'],
  ['西柚', 'grapefruit', 'Grapefruit', 'pamplemousse', 'grapefruit', 'pompelmo'],
  ['檸檬', 'lemons', 'Zitronen', 'citrons', 'citroenen', 'limoni'],
  ['青檸', 'limes', 'Limetten', 'citrons verts', 'limoenen', 'lime'],
  ['芒果', 'mango', 'Mango', 'mangue', 'mango', 'mango'],
  ['牛油果', 'avocado', 'Avocado', 'avocat', 'avocado', 'avocado'],
  ['蜜瓜', 'melon', 'Melone', 'melon', 'meloen', 'melone'],
  ['西瓜', 'watermelon', 'Wassermelone', 'pastèque', 'watermeloen', 'anguria'],
  ['水蜜桃', 'peaches', 'Pfirsiche', 'pêches', 'perziken', 'pesche'],
  ['啤梨', 'pears', 'Birnen', 'poires', 'peren', 'pere'],
  ['蘋果', 'apples', 'Äpfel', 'pommes', 'appels', 'mele'],
  ['西蘭花', 'broccoli', 'Brokkoli', 'brocoli', 'broccoli', 'broccoli'],
  ['椰菜花', 'cauliflower', 'Blumenkohl', 'chou-fleur', 'bloemkool', 'cavolfiore'],
  ['椰菜|捲心菜', 'cabbage', 'Weißkohl', 'chou', 'witte kool', 'cavolo cappuccio'],
  ['生菜', 'lettuce', 'Kopfsalat', 'laitue', 'sla', 'lattuga'],
  ['菠菜', 'spinach', 'Spinat', 'épinards', 'spinazie', 'spinaci'],
  ['青瓜', 'cucumber', 'Gurke', 'concombre', 'komkommer', 'cetriolo'],
  ['紅蘿蔔|甘筍', 'carrots', 'Karotten', 'carottes', 'wortelen', 'carote'],
  ['粟米', 'sweetcorn|corn', 'Mais', 'maïs', 'mais', 'mais'],
  ['蘑菇|磨菇', 'mushrooms', 'Champignons', 'champignons', 'champignons', 'funghi'],
  ['燈籠椒|甜椒', 'peppers|bell peppers', 'Paprika', 'poivrons', 'paprika', 'peperoni'],
  ['辣椒', 'chillies|chilli', 'Chili', 'piment', 'chilipeper', 'peperoncino'],
  ['薑', 'ginger', 'Ingwer', 'gingembre', 'gember', 'zenzero'],
  ['蒜頭|大蒜', 'garlic', 'Knoblauch', 'ail', 'knoflook', 'aglio'],
  ['番薯|蕃薯', 'sweet potatoes', 'Süßkartoffeln', 'patates douces', 'zoete aardappelen', 'patate dolci'],
  ['南瓜', 'pumpkin|squash', 'Kürbis', 'potiron', 'pompoen', 'zucca'],
  ['豆腐', 'tofu', 'Tofu', 'tofu', 'tofu', 'tofu'],
  ['芽菜', 'bean sprouts', 'Sojasprossen', 'pousses de soja', 'taugé', 'germogli di soia'],
  // meat & seafood
  ['雞翼', 'chicken wings', 'Hähnchenflügel', 'ailes de poulet', 'kippenvleugels', 'ali di pollo'],
  ['雞髀|雞腿', 'chicken thighs|chicken legs', 'Hähnchenschenkel', 'cuisses de poulet', 'kippendijen', 'cosce di pollo'],
  ['豬扒', 'pork chops', 'Schweinekoteletts', 'côtes de porc', 'karbonades', 'braciole di maiale'],
  ['牛扒', 'steak', 'Steak', 'steak', 'biefstuk', 'bistecca'],
  ['免治牛肉|牛肉碎', 'beef mince|minced beef', 'Rinderhackfleisch', 'bœuf haché', 'rundergehakt', 'macinato di manzo'],
  ['免治豬肉|豬肉碎', 'pork mince|minced pork', 'Schweinehackfleisch', 'porc haché', 'varkensgehakt', 'macinato di maiale'],
  ['羊肉', 'lamb', 'Lammfleisch', 'agneau', 'lamsvlees', 'agnello'],
  ['煙肉', 'bacon', 'Bacon', 'bacon', 'spek', 'pancetta'],
  ['火腿', 'ham', 'Schinken', 'jambon', 'ham', 'prosciutto cotto'],
  ['腸仔|香腸', 'sausages', 'Würstchen', 'saucisses', 'worstjes', 'salsicce'],
  ['午餐肉', 'luncheon meat|spam', 'Frühstücksfleisch', 'luncheon meat', 'lunchmeat', 'carne in scatola'],
  ['魚蛋|魚丸', 'fish balls', 'Fischbällchen', 'boulettes de poisson', 'visballetjes', 'polpette di pesce'],
  ['蝦', 'prawns|shrimp', 'Garnelen', 'crevettes', 'garnalen', 'gamberi'],
  ['吞拿魚', 'tuna', 'Thunfisch', 'thon', 'tonijn', 'tonno'],
  ['沙甸魚', 'sardines', 'Sardinen', 'sardines', 'sardines', 'sardine'],
  ['鱈魚', 'cod', 'Kabeljau', 'cabillaud', 'kabeljauw', 'merluzzo'],
  ['帶子', 'scallops', 'Jakobsmuscheln', 'noix de Saint-Jacques', 'sint-jakobsschelpen', 'capesante'],
  ['青口', 'mussels', 'Miesmuscheln', 'moules', 'mosselen', 'cozze'],
  ['蟹', 'crab', 'Krabbe', 'crabe', 'krab', 'granchio'],
  ['魷魚', 'squid', 'Tintenfisch', 'calamar', 'inktvis', 'calamari'],
  // dairy, bakery & snacks
  ['忌廉芝士', 'cream cheese', 'Frischkäse', 'fromage frais', 'roomkaas', 'formaggio spalmabile'],
  ['忌廉', 'cream', 'Sahne', 'crème', 'room', 'panna'],
  ['淡奶', 'evaporated milk', 'Kondensmilch', 'lait concentré non sucré', 'koffiemelk', 'latte evaporato'],
  ['煉奶', 'condensed milk', 'gezuckerte Kondensmilch', 'lait concentré sucré', 'gecondenseerde melk', 'latte condensato'],
  ['脫脂奶', 'skimmed milk', 'Magermilch', 'lait écrémé', 'magere melk', 'latte scremato'],
  ['低脂奶', 'semi-skimmed milk', 'fettarme Milch', 'lait demi-écrémé', 'halfvolle melk', 'latte parzialmente scremato'],
  ['全脂奶', 'whole milk', 'Vollmilch', 'lait entier', 'volle melk', 'latte intero'],
  ['鮮奶', 'fresh milk', 'Frischmilch', 'lait frais', 'verse melk', 'latte fresco'],
  ['方包|吐司', 'sliced bread', 'Toastbrot', 'pain de mie', 'casinobrood', 'pancarrè'],
  ['蛋糕', 'cake', 'Kuchen', 'gâteau', 'taart', 'torta'],
  ['薯條', 'frozen chips|fries|french fries', 'Pommes frites', 'frites', 'friet', 'patatine fritte'],
  ['爆谷', 'popcorn', 'Popcorn', 'pop-corn', 'popcorn', 'popcorn'],
  ['果仁', 'nuts', 'Nüsse', 'noix', 'noten', 'frutta secca'],
  ['杏仁', 'almonds', 'Mandeln', 'amandes', 'amandelen', 'mandorle'],
  ['核桃', 'walnuts', 'Walnüsse', 'noix', 'walnoten', 'noci'],
  ['花生', 'peanuts', 'Erdnüsse', 'cacahuètes', "pinda's", 'arachidi'],
  ['軟糖', 'gummies|jelly sweets', 'Fruchtgummi', 'bonbons gélifiés', 'winegums', 'caramelle gommose'],
  ['糖果', 'sweets|candy', 'Süßigkeiten', 'bonbons', 'snoep', 'caramelle'],
  ['香口膠', 'chewing gum', 'Kaugummi', 'chewing-gum', 'kauwgom', 'gomma da masticare'],
  ['梳打餅', 'crackers', 'Cracker', 'crackers', 'crackers', 'cracker'],
  ['燕麥|麥皮', 'porridge oats|oats', 'Haferflocken', "flocons d'avoine", 'havermout', "fiocchi d'avena"],
  ['米粉', 'rice noodles', 'Reisnudeln', 'nouilles de riz', 'rijstnoedels', 'spaghetti di riso'],
  ['烏冬', 'udon', 'Udon', 'udon', 'udon', 'udon'],
  ['餃子', 'dumplings|gyoza', 'Gyoza', 'gyoza', 'gyoza', 'gyoza'],
  // sauces & cooking
  ['豉油|醬油', 'soy sauce', 'Sojasauce', 'sauce soja', 'sojasaus', 'salsa di soia'],
  ['蠔油', 'oyster sauce', 'Austernsauce', "sauce d'huître", 'oestersaus', "salsa d'ostriche"],
  ['茄汁', 'ketchup', 'Ketchup', 'ketchup', 'ketchup', 'ketchup'],
  ['沙律醬|蛋黃醬', 'mayonnaise', 'Mayonnaise', 'mayonnaise', 'mayonaise', 'maionese'],
  ['芥末|黃芥辣', 'mustard', 'Senf', 'moutarde', 'mosterd', 'senape'],
  ['醋', 'vinegar', 'Essig', 'vinaigre', 'azijn', 'aceto'],
  ['胡椒粉|胡椒', 'black pepper|pepper', 'Pfeffer', 'poivre', 'peper', 'pepe'],
  ['麻油', 'sesame oil', 'Sesamöl', 'huile de sésame', 'sesamolie', 'olio di sesamo'],
  ['食油|菜油', 'vegetable oil|cooking oil', 'Speiseöl', 'huile végétale', 'plantaardige olie', 'olio di semi'],
  ['粟粉', 'cornflour', 'Speisestärke', 'fécule de maïs', 'maizena', 'amido di mais'],
  ['咖喱', 'curry', 'Curry', 'curry', 'curry', 'curry'],
  // drinks
  ['奶茶', 'milk tea', 'Milchtee', 'thé au lait', 'melkthee', 'tè al latte'],
  ['綠茶', 'green tea', 'grüner Tee', 'thé vert', 'groene thee', 'tè verde'],
  ['紅茶', 'black tea', 'Schwarztee', 'thé noir', 'zwarte thee', 'tè nero'],
  ['檸檬茶', 'lemon tea|iced lemon tea', 'Eistee Zitrone', 'thé glacé citron', 'ijsthee citroen', 'tè al limone'],
  ['梳打水|氣泡水', 'sparkling water|soda water', 'Sprudelwasser', 'eau gazeuse', 'bruisend water', 'acqua frizzante'],
  ['蒸餾水|樽裝水', 'bottled water|still water', 'stilles Wasser', 'eau plate', 'plat water', 'acqua naturale'],
  ['能量飲品', 'energy drink', 'Energydrink', 'boisson énergisante', 'energiedrank', 'bevanda energetica'],
  ['威士忌', 'whisky', 'Whisky', 'whisky', 'whisky', 'whisky'],
  ['香檳', 'champagne', 'Champagner', 'champagne', 'champagne', 'champagne'],
  ['氈酒', 'gin', 'Gin', 'gin', 'gin', 'gin'],
  ['伏特加', 'vodka', 'Wodka', 'vodka', 'wodka', 'vodka'],
  ['清酒', 'sake', 'Sake', 'saké', 'sake', 'sakè'],
  ['蘋果酒', 'cider', 'Cider', 'cidre', 'cider', 'sidro'],
  // words that describe the product
  ['有機', 'organic', 'Bio', 'bio', 'biologisch', 'bio'],
  ['急凍|冷凍', 'frozen', 'tiefgekühlt', 'surgelé', 'diepvries', 'surgelato'],
  ['無糖', 'sugar free|sugar-free', 'zuckerfrei', 'sans sucre', 'suikervrij', 'senza zucchero'],
  ['低糖', 'low sugar', 'zuckerreduziert', 'allégé en sucre', 'minder suiker', 'poco zucchero'],
  ['二手', 'second hand|used', 'gebraucht', "d'occasion", 'tweedehands', 'usato'],
  ['男裝', "men's", 'Herren', 'homme', 'heren', 'uomo'],
  ['女裝', "women's", 'Damen', 'femme', 'dames', 'donna'],
  ['童裝|兒童', "kids'|children's", 'Kinder', 'enfant', 'kinder', 'bambini'],
  ['無線', 'wireless', 'kabellos', 'sans fil', 'draadloos', 'wireless'],
  ['便攜|便攜式|攜帶式', 'portable', 'tragbar', 'portable', 'draagbaar', 'portatile'],
  ['迷你', 'mini', 'Mini', 'mini', 'mini', 'mini'],
  ['防水', 'waterproof', 'wasserdicht', 'étanche', 'waterdicht', 'impermeabile'],
  ['不銹鋼|不鏽鋼', 'stainless steel', 'Edelstahl', 'inox', 'roestvrij staal', 'acciaio inox'],
  ['補充裝', 'refill', 'Nachfüllpack', 'recharge', 'navulling', 'ricarica'],
  ['家庭裝', 'family pack', 'Familienpackung', 'format familial', 'familieverpakking', 'confezione famiglia'],
  ['套裝', 'set', 'Set', 'coffret', 'set', 'set'],
  ['白色', 'white', 'weiß', 'blanc', 'wit', 'bianco'],
  ['黑色', 'black', 'schwarz', 'noir', 'zwart', 'nero'],
  ['灰色', 'grey|gray', 'grau', 'gris', 'grijs', 'grigio'],
  ['紅色', 'red', 'rot', 'rouge', 'rood', 'rosso'],
  ['海軍藍', 'navy', 'marineblau', 'bleu marine', 'marineblauw', 'blu navy'],
  ['藍色', 'blue', 'blau', 'bleu', 'blauw', 'blu'],
  ['綠色', 'green', 'grün', 'vert', 'groen', 'verde'],
  ['黃色', 'yellow', 'gelb', 'jaune', 'geel', 'giallo'],
  ['粉紅色|粉紅', 'pink', 'rosa', 'rose', 'roze', 'rosa'],
  ['紫色', 'purple', 'lila', 'violet', 'paars', 'viola'],
  ['啡色|咖啡色|棕色', 'brown', 'braun', 'marron', 'bruin', 'marrone'],
  ['米色', 'beige', 'beige', 'beige', 'beige', 'beige'],
  ['銀色', 'silver', 'silber', 'argenté', 'zilver', 'argento'],
  ['金色', 'gold', 'gold', 'doré', 'goud', 'oro'],
  // electronics
  ['無線耳機|藍牙耳機', 'wireless earbuds', 'kabellose Kopfhörer', 'écouteurs sans fil', 'draadloze oordopjes', 'auricolari wireless'],
  ['耳機', 'headphones', 'Kopfhörer', 'casque audio', 'koptelefoon', 'cuffie'],
  ['手機', 'smartphone|mobile phone', 'Smartphone', 'smartphone', 'smartphone', 'smartphone'],
  ['平板電腦', 'tablet', 'Tablet', 'tablette', 'tablet', 'tablet'],
  ['手提電腦|筆記本電腦', 'laptop', 'Laptop', 'ordinateur portable', 'laptop', 'portatile'],
  ['電視', 'tv|television', 'Fernseher', 'téléviseur', 'televisie', 'televisore'],
  ['相機', 'camera', 'Kamera', 'appareil photo', 'camera', 'fotocamera'],
  ['尿袋|充電寶|行動電源', 'power bank', 'Powerbank', 'batterie externe', 'powerbank', 'power bank'],
  ['充電器|叉電器', 'charger', 'Ladegerät', 'chargeur', 'oplader', 'caricabatterie'],
  ['喇叭|音箱', 'speaker', 'Lautsprecher', 'enceinte', 'speaker', 'altoparlante'],
  ['顯示屏|電腦螢幕', 'monitor', 'Monitor', 'écran', 'monitor', 'monitor'],
  ['遊戲機', 'game console', 'Spielkonsole', 'console de jeux', 'spelcomputer', 'console'],
  ['智能手錶', 'smartwatch', 'Smartwatch', 'montre connectée', 'smartwatch', 'smartwatch'],
  ['iPhone|蘋果手機', 'iPhone', 'iPhone', 'iPhone', 'iPhone', 'iPhone'],
  ['iPad|蘋果平板', 'iPad', 'iPad', 'iPad', 'iPad', 'iPad'],
  ['MacBook|蘋果電腦', 'MacBook', 'MacBook', 'MacBook', 'MacBook', 'MacBook'],
  ['AirPods|蘋果耳機', 'AirPods', 'AirPods', 'AirPods', 'AirPods', 'AirPods'],
  ['Apple Watch|蘋果手錶', 'Apple Watch', 'Apple Watch', 'Apple Watch', 'Apple Watch', 'Apple Watch'],
  ['Galaxy Watch', 'Galaxy Watch', 'Galaxy Watch', 'Galaxy Watch', 'Galaxy Watch', 'Galaxy Watch'],
  ['Apple TV', 'Apple TV', 'Apple TV', 'Apple TV', 'Apple TV', 'Apple TV'],
  ['Fire TV', 'Fire TV', 'Fire TV', 'Fire TV', 'Fire TV', 'Fire TV'],
  ['叉電線|充電線|數據線', 'charging cable', 'Ladekabel', 'câble de charge', 'oplaadkabel', 'cavo di ricarica'],
  ['拖板', 'extension lead', 'Steckdosenleiste', 'multiprise', 'stekkerdoos', 'ciabatta elettrica'],
  ['轉插|轉換插頭|萬能插頭', 'travel adapter|plug adapter', 'Reiseadapter', 'adaptateur de voyage', 'reisstekker', 'adattatore da viaggio'],
  ['滑鼠|鼠標', 'mouse', 'Maus', 'souris', 'muis', 'mouse'],
  ['鍵盤', 'keyboard', 'Tastatur', 'clavier', 'toetsenbord', 'tastiera'],
  ['記憶卡', 'memory card', 'Speicherkarte', 'carte mémoire', 'geheugenkaart', 'scheda di memoria'],
  ['手指', 'flash drive', 'USB-Stick', 'clé USB', 'USB-stick', 'chiavetta USB'],
  ['外置硬碟|外置硬盤', 'external hard drive', 'externe Festplatte', 'disque dur externe', 'externe harde schijf', 'disco rigido esterno'],
  ['硬碟|硬盤', 'hard drive', 'Festplatte', 'disque dur', 'harde schijf', 'disco rigido'],
  ['路由器', 'router', 'Router', 'routeur', 'router', 'router'],
  ['打印機', 'printer', 'Drucker', 'imprimante', 'printer', 'stampante'],
  ['墨盒', 'ink cartridge', 'Druckerpatrone', "cartouche d'encre", 'inktcartridge', "cartuccia d'inchiostro"],
  ['手機殼|手機套', 'phone case', 'Handyhülle', 'coque de téléphone', 'telefoonhoesje', 'cover per telefono'],
  ['保護貼|芒貼|螢幕貼', 'screen protector', 'Displayschutzfolie', "protection d'écran", 'screenprotector', 'pellicola protettiva'],
  ['三腳架', 'tripod', 'Stativ', 'trépied', 'statief', 'treppiede'],
  ['鏡頭', 'camera lens|lens', 'Objektiv', 'objectif', 'objectief', 'obiettivo'],
  ['無人機', 'drone', 'Drohne', 'drone', 'drone', 'drone'],
  ['投影機', 'projector', 'Beamer', 'vidéoprojecteur', 'beamer', 'proiettore'],
  ['手掣', 'controller', 'Controller', 'manette', 'controller', 'controller'],
  ['手環', 'fitness tracker', 'Fitnesstracker', "bracelet d'activité", 'activity tracker', 'smartband'],
  ['電子書', 'e-reader', 'E-Reader', 'liseuse', 'e-reader', 'e-reader'],
  // other
  ['行李箱|喼', 'suitcase', 'Koffer', 'valise', 'koffer', 'valigia'],
  ['背囊|背包', 'backpack|rucksack', 'Rucksack', 'sac à dos', 'rugzak', 'zaino'],
  ['波鞋|運動鞋', 'trainers|sneakers', 'Sneaker', 'baskets', 'sneakers', 'scarpe da ginnastica'],
  ['外套', 'jacket', 'Jacke', 'veste', 'jas', 'giacca'],
  ['太陽眼鏡', 'sunglasses', 'Sonnenbrille', 'lunettes de soleil', 'zonnebril', 'occhiali da sole'],
  ['手錶', 'watch', 'Uhr', 'montre', 'horloge', 'orologio'],
  ['玩具', 'toys', 'Spielzeug', 'jouets', 'speelgoed', 'giocattoli'],
  // clothing & accessories
  ['冷衫|毛衣', 'jumper|sweater', 'Pullover', 'pull', 'trui', 'maglione'],
  ['衛衣', 'hoodie|sweatshirt', 'Hoodie', 'sweat à capuche', 'hoodie', 'felpa'],
  ['羽絨褸|羽絨', 'down jacket|puffer jacket', 'Daunenjacke', 'doudoune', 'donsjas', 'piumino'],
  ['風褸', 'windbreaker', 'Windjacke', 'coupe-vent', 'windjack', 'giacca a vento'],
  ['大褸|褸', 'coat', 'Mantel', 'manteau', 'jas', 'cappotto'],
  ['恤衫|襯衫', 'shirt', 'Hemd', 'chemise', 'overhemd', 'camicia'],
  ['恤', 't-shirt|t shirt|tee', 'T-Shirt', 't-shirt', 'T-shirt', 't-shirt'],
  ['牛仔褲', 'jeans', 'Jeans', 'jean', 'spijkerbroek', 'jeans'],
  ['短褲', 'shorts', 'Shorts', 'short', 'korte broek', 'pantaloncini'],
  ['內褲', 'underwear', 'Unterhose', 'slip', 'onderbroek', 'mutande'],
  ['打底褲', 'leggings', 'Leggings', 'legging', 'legging', 'leggings'],
  ['運動褲', 'joggers|tracksuit bottoms', 'Jogginghose', 'pantalon de jogging', 'joggingbroek', 'pantaloni sportivi'],
  ['絲襪|襪褲', 'tights', 'Strumpfhose', 'collant', 'panty', 'collant'],
  ['褲', 'trousers', 'Hose', 'pantalon', 'broek', 'pantaloni'],
  ['襪', 'socks', 'Socken', 'chaussettes', 'sokken', 'calzini'],
  ['連身裙|裙', 'dress', 'Kleid', 'robe', 'jurk', 'vestito'],
  ['半截裙|短裙', 'skirt', 'Rock', 'jupe', 'rok', 'gonna'],
  ['背心', 'vest|tank top', 'Tanktop', 'débardeur', 'hemdje', 'canottiera'],
  ['胸圍', 'bra', 'BH', 'soutien-gorge', 'beha', 'reggiseno'],
  ['泳衣', 'swimsuit', 'Badeanzug', 'maillot de bain', 'badpak', 'costume da bagno'],
  ['頸巾|圍巾', 'scarf', 'Schal', 'écharpe', 'sjaal', 'sciarpa'],
  ['手套', 'gloves', 'Handschuhe', 'gants', 'handschoenen', 'guanti'],
  ['冷帽', 'beanie', 'Mütze', 'bonnet', 'muts', 'berretto'],
  ['鴨舌帽', 'baseball cap', 'Basecap', 'casquette', 'pet', 'cappellino'],
  ['帽', 'hat', 'Hut', 'chapeau', 'hoed', 'cappello'],
  ['皮帶', 'belt', 'Gürtel', 'ceinture', 'riem', 'cintura'],
  ['銀包', 'wallet|purse', 'Geldbörse', 'portefeuille', 'portemonnee', 'portafoglio'],
  ['手袋', 'handbag', 'Handtasche', 'sac à main', 'handtas', 'borsa'],
  ['斜孭袋', 'crossbody bag', 'Umhängetasche', 'sac bandoulière', 'schoudertas', 'borsa a tracolla'],
  ['環保袋', 'tote bag|reusable bag', 'Stofftasche', 'tote bag', 'shopper', 'borsa di tela'],
  ['皮鞋', 'leather shoes', 'Lederschuhe', 'chaussures en cuir', 'leren schoenen', 'scarpe in pelle'],
  ['高踭鞋', 'high heels', 'High Heels', 'talons hauts', 'hakken', 'scarpe con tacco'],
  ['涼鞋', 'sandals', 'Sandalen', 'sandales', 'sandalen', 'sandali'],
  ['拖鞋', 'slippers', 'Hausschuhe', 'chaussons', 'pantoffels', 'pantofole'],
  ['行山鞋', 'hiking boots', 'Wanderschuhe', 'chaussures de randonnée', 'wandelschoenen', 'scarpe da trekking'],
  ['靴', 'boots', 'Stiefel', 'bottes', 'laarzen', 'stivali'],
  ['鞋', 'shoes', 'Schuhe', 'chaussures', 'schoenen', 'scarpe'],
  ['老花鏡', 'reading glasses', 'Lesebrille', 'lunettes de lecture', 'leesbril', 'occhiali da lettura'],
  ['眼鏡', 'glasses', 'Brille', 'lunettes', 'bril', 'occhiali'],
  ['頸鏈', 'necklace', 'Halskette', 'collier', 'ketting', 'collana'],
  ['耳環', 'earrings', 'Ohrringe', "boucles d'oreilles", 'oorbellen', 'orecchini'],
  ['手鏈', 'bracelet', 'Armband', 'bracelet', 'armband', 'braccialetto'],
  ['雨遮|雨傘|遮', 'umbrella', 'Regenschirm', 'parapluie', 'paraplu', 'ombrello'],
  // travel, sport & leisure
  ['旅行袋', 'holdall|travel bag', 'Reisetasche', 'sac de voyage', 'reistas', 'borsone da viaggio'],
  ['頸枕', 'travel pillow|neck pillow', 'Nackenkissen', 'coussin de voyage', 'nekkussen', 'cuscino da viaggio'],
  ['行山杖', 'trekking poles|walking poles', 'Wanderstöcke', 'bâtons de randonnée', 'wandelstokken', 'bastoncini da trekking'],
  ['帳篷|營幕', 'tent', 'Zelt', 'tente', 'tent', 'tenda'],
  ['睡袋', 'sleeping bag', 'Schlafsack', 'sac de couchage', 'slaapzak', 'sacco a pelo'],
  ['電動滑板車', 'electric scooter', 'E-Scooter', 'trottinette électrique', 'elektrische step', 'monopattino elettrico'],
  ['滑板車', 'scooter|kick scooter', 'Tretroller', 'trottinette', 'step', 'monopattino'],
  ['單車', 'bike|bicycle', 'Fahrrad', 'vélo', 'fiets', 'bicicletta'],
  ['瑜伽墊', 'yoga mat', 'Yogamatte', 'tapis de yoga', 'yogamat', 'tappetino yoga'],
  ['啞鈴', 'dumbbells', 'Hanteln', 'haltères', 'halters', 'manubri'],
  ['網球拍', 'tennis racket', 'Tennisschläger', 'raquette de tennis', 'tennisracket', 'racchetta da tennis'],
  ['砌圖', 'jigsaw puzzle|jigsaw', 'Puzzle', 'puzzle', 'puzzel', 'puzzle'],
  ['積木', 'building blocks', 'Bausteine', 'jeu de construction', 'bouwstenen', 'mattoncini'],
  ['公仔', 'soft toy|plush toy', 'Kuscheltier', 'peluche', 'knuffel', 'peluche'],
  ['文具', 'stationery', 'Schreibwaren', 'papeterie', 'schrijfwaren', 'cancelleria'],
  ['原子筆', 'ballpoint pen|biro', 'Kugelschreiber', 'stylo bille', 'balpen', 'penna a sfera'],
  ['筆記簿', 'notebook', 'Notizbuch', 'carnet', 'notitieboek', 'quaderno'],
  ['禮物卡', 'gift card', 'Geschenkkarte', 'carte cadeau', 'cadeaukaart', 'carta regalo'],
  // cities (hotel search)
  ['倫敦', 'London', 'London', 'Londres', 'Londen', 'Londra'],
  ['巴黎', 'Paris', 'Paris', 'Paris', 'Parijs', 'Parigi'],
  ['曼徹斯特|曼城', 'Manchester', 'Manchester', 'Manchester', 'Manchester', 'Manchester'],
  ['愛丁堡', 'Edinburgh', 'Edinburgh', 'Édimbourg', 'Edinburgh', 'Edimburgo'],
  ['利物浦', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool', 'Liverpool'],
  ['伯明翰', 'Birmingham', 'Birmingham', 'Birmingham', 'Birmingham', 'Birmingham'],
  ['牛津', 'Oxford', 'Oxford', 'Oxford', 'Oxford', 'Oxford'],
  ['劍橋', 'Cambridge', 'Cambridge', 'Cambridge', 'Cambridge', 'Cambridge'],
  ['柏林', 'Berlin', 'Berlin', 'Berlin', 'Berlijn', 'Berlino'],
  ['慕尼黑', 'Munich', 'München', 'Munich', 'München', 'Monaco di Baviera'],
  ['法蘭克福', 'Frankfurt', 'Frankfurt', 'Francfort', 'Frankfurt', 'Francoforte'],
  ['羅馬', 'Rome', 'Rom', 'Rome', 'Rome', 'Roma'],
  ['米蘭', 'Milan', 'Mailand', 'Milan', 'Milaan', 'Milano'],
  ['威尼斯', 'Venice', 'Venedig', 'Venise', 'Venetië', 'Venezia'],
  ['佛羅倫斯|翡冷翠', 'Florence', 'Florenz', 'Florence', 'Florence', 'Firenze'],
  ['巴塞隆拿|巴塞羅那', 'Barcelona', 'Barcelona', 'Barcelone', 'Barcelona', 'Barcellona'],
  ['馬德里', 'Madrid', 'Madrid', 'Madrid', 'Madrid', 'Madrid'],
  ['阿姆斯特丹', 'Amsterdam', 'Amsterdam', 'Amsterdam', 'Amsterdam', 'Amsterdam'],
  ['布魯塞爾', 'Brussels', 'Brüssel', 'Bruxelles', 'Brussel', 'Bruxelles'],
  ['維也納', 'Vienna', 'Wien', 'Vienne', 'Wenen', 'Vienna'],
  ['蘇黎世', 'Zurich', 'Zürich', 'Zurich', 'Zürich', 'Zurigo'],
  ['布拉格', 'Prague', 'Prag', 'Prague', 'Praag', 'Praga'],
  ['里斯本', 'Lisbon', 'Lissabon', 'Lisbonne', 'Lissabon', 'Lisbona'],
  ['都柏林', 'Dublin', 'Dublin', 'Dublin', 'Dublin', 'Dublino'],
  ['香港', 'Hong Kong', 'Hongkong', 'Hong Kong', 'Hongkong', 'Hong Kong'],
];
